### PR TITLE
Add travis CI

### PR DESCRIPTION
**Pull request by ziima**
I suggest to use Travis (or other) CI to run tests. If you agree with Travis, you might need to enable it at https://travis-ci.org/account/repositories.

### CODE REVIEW

**Comment by cjwelborn** [comment]
I think it's a good idea. I will enable whatever configuration I need to and merge this (probably this weekend).

**Review by cjwelborn — APPROVED** [review]
I don't know Travis very well. I've just now started looking at GitHub Actions/Workflows. This looks like it just runs the tox tests under a normal user account, which is way better than nothing. I'm gonna merge it. Thank you for taking the time.

**Comment by cjwelborn** [comment]
@ziima, I was seeing some failures for Travis because of missing interpreters (3.7 & 3.8). I tweaked `.travis.yml` to use `tox-travis` and it seems to work.

Thanks again for your help.

**Comment by ziima** [comment]
Nice, I've probably deleted too many things :)

**Pull request merged**
