### PR TITLE
Use tox for testing

### PR DESCRIPTION
**Pull request by ziima**
I suggest to use tox instead of a custom script for testing. It's way easier to maintain ;-)

### CODE REVIEW

**Comment by cjwelborn** [comment]
I'll look into it. I know what it is, I've just never tried it out on a real project. Let me see what I can do.

**Comment by ziima** [comment]
Just run `tox` and observe :-)

**Comment by cjwelborn** [comment]
I wasn't paying close enough attention when I read this (at work). Of course I'll merge it. Thank you.

**Comment by cjwelborn** [comment]
I thought I was reading an "issue" earlier today, I didn't realize you had already did the work. I'm working on issue #7 right now. Nearly done.

**Pull request merged**
